name: Build and deploy Node.js app to Azure Web App - deploy-azure-jorge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6493FDDA15B944939F26C9E7389E11D2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1A8146E79B0D492CA7202FD5714FFB3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C8303020D152405BB43ED8B6260A45ED }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: deployazurejorgeacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: deployazurejorgeacr.azurecr.io/api-azure-deploy:${{ github.sha }}

      - name: Configure App Service
        run: |
          az webapp config container set --name deploy-azure-jorge --resource-group deploy-azure-jorge_group --container-image-name deployazurejorgeacr.azurecr.io/api-azure-deploy:${{ github.sha }}
          az webapp config appsettings set --name deploy-azure-jorge --resource-group deploy-azure-jorge_group --settings "WEBSITES_PORT=3000" "WEBSITES_CONTAINER_START_TIME_LIMIT=1800" "NODE_ENV=production" "PORT=3000"          
          az webapp restart --name deploy-azure-jorge --resource-group deploy-azure-jorge_group